// <auto-generated />
using System;
using GestionNutricion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionNutricion.Infrastructure.Migrations
{
    [DbContext(typeof(GestionNutricionContext))]
    [Migration("20230924222843_user-id")]
    partial class userid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionNutricion.Core.Entitys.DietaryPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breakfast")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietaryPlan", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.MainCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dessert")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdDietaryPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdMainCourseType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDietaryPlan");

                    b.HasIndex("IdMainCourseType");

                    b.ToTable("MainCourse", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.MainCourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("MainCourseType", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.PlanSnack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdDietaryPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdSnackTime")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDietaryPlan");

                    b.HasIndex("IdSnackTime");

                    b.ToTable("PlanSnack", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.Snack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdSnackTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSnackTime");

                    b.ToTable("Snack", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.SnackTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SnackTime", (string)null);
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.MainCourse", b =>
                {
                    b.HasOne("GestionNutricion.Core.Entitys.DietaryPlan", "DietaryPlan")
                        .WithMany("MainCourses")
                        .HasForeignKey("IdDietaryPlan")
                        .IsRequired();

                    b.HasOne("GestionNutricion.Core.Entitys.MainCourseType", "MainCourseType")
                        .WithMany("MainCourses")
                        .HasForeignKey("IdMainCourseType")
                        .IsRequired();

                    b.Navigation("DietaryPlan");

                    b.Navigation("MainCourseType");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.PlanSnack", b =>
                {
                    b.HasOne("GestionNutricion.Core.Entitys.DietaryPlan", "DietaryPlan")
                        .WithMany("PlanSnacks")
                        .HasForeignKey("IdDietaryPlan")
                        .IsRequired();

                    b.HasOne("GestionNutricion.Core.Entitys.SnackTime", "SnackTime")
                        .WithMany("PlanSnacks")
                        .HasForeignKey("IdSnackTime");

                    b.Navigation("DietaryPlan");

                    b.Navigation("SnackTime");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.Snack", b =>
                {
                    b.HasOne("GestionNutricion.Core.Entitys.SnackTime", "SnackTime")
                        .WithMany("Snacks")
                        .HasForeignKey("IdSnackTime");

                    b.Navigation("SnackTime");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.DietaryPlan", b =>
                {
                    b.Navigation("MainCourses");

                    b.Navigation("PlanSnacks");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.MainCourseType", b =>
                {
                    b.Navigation("MainCourses");
                });

            modelBuilder.Entity("GestionNutricion.Core.Entitys.SnackTime", b =>
                {
                    b.Navigation("PlanSnacks");

                    b.Navigation("Snacks");
                });
#pragma warning restore 612, 618
        }
    }
}
